# Generated by Django 4.2.2 on 2024-05-16 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_transaction_quantity_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('total_share', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('average_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_portfolios',
                'ordering': ['stock__code'],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
