# Generated by Django 4.2.2 on 2024-07-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_order',
            field=models.BooleanField(default=True),
        ),
    ]
