# Generated by Django 4.2.2 on 2024-07-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_is_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trades',
            field=models.ManyToManyField(blank=True, to='core.transaction'),
        ),
    ]
